addopts = -p no:warnings -p pytest_asyncio -p pytest_mock
asyncio_mode = auto
testpaths =
    tests/basic
    tests/tools    
    tests/help
    tests/hooks
    tests/mcp
    tests/browser
    tests/scrape

env =
    CECLI_TUI=false
