theme: just-the-docs
url: "https://cecli.dev"

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed

defaults:
  - scope:
      path: "README.md"
      type: "pages"
    values:
      description: "cecli speaks fluent terminal"

exclude:
  - "tmp*"
  - "**/tmp*"
  - OLD
  - "**/OLD/**"
  - "OLD/**"
  - vendor
  - feed.xml

aux_links:
  "GitHub":
    - "https://github.com/dwash96/cecli"
  "Discord":
    - "https://discord.gg/AX9ZEA7nJn"
  "Support":
    - "https://ko-fi.com/cecli"

nav_external_links:
  - title: "GitHub"
    url: "https://github.com/dwash96/cecli"
  - title: "Discord"
    url: "https://discord.gg/AX9ZEA7nJn"
  - title: "Support"
    url: "https://ko-fi.com/cecli"

repository: dwash96/cecli

callouts:
  tip:
    title: Tip
    color: green
  note:
    title: Note
    color: yellow

# Custom CSS for our table of contents
kramdown:
  syntax_highlighter_opts:
    css_class: highlight
    
sass:
  sass_dir: _sass
  style: compressed
  
# Additional CSS
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  
